name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update old texfile
        uses: canastro/copy-action@0.0.2
        with:
          source: "diff/new.tex"
          target: "diff/old.tex"
      - name: Update new texfile
        uses: canastro/copy-action@0.0.2
        with:
          source: "main.tex"
          target: "diff/new.tex"
      - name: Install and Run latexdiff
        run: |
          sudo apt-get install latexdiff
          latexdiff --flatten diff/old.tex diff/new.tex > diff/diff.tex
      - name: Build LaTeX documents
        uses: 3rdJCG/latex-build-langja@master
        with:
          root_file: diff/diff.tex
          args: -r .latexmkrc
      - name: Restore pdf artifact
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: diff/diff.pdf
