name: Build LaTeX document
on: 
  push:
    tags: 
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Build LaTeX documents
        uses: 3rdJCG/latex-build-langja@master
        with:
          root_file: main.tex
          args: -r .latexmkrc
      - name: Install and Run latexdiff
        run: |
          sudo apt-get install latexdiff 
          latexdiff-vc -e utf8 -t CFONT --git --flatten --force -r HEAD~1 main.tex
          mv main-diffHEAD~1.tex diff.tex
      - name: Build LaTeX-diff documents
        uses: 3rdJCG/latex-build-langja@master
        with:
          root_file: diff.tex
          args: -r .latexmkrc
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{github.ref}}
          release_name: Release ${{ github.ref }}
          body: |
            Compiled PDF ${{github.ref}}
          draft: false
          prerelease: false
      - name: Upload Release Asset main
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./main.pdf
          asset_name: main.pdf
          asset_content_type: application/pdf
      - name: Upload Release Asset diff
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./diff.pdf
          asset_name: diff.pdf
          asset_content_type: application/pdf
